# This flake was initially generated by fh, the CLI for FlakeHub (version 0.1.12)
{
  # A helpful description of your flake
  description = "FlakeHub store path outputs example project";

  # Flake inputs
  inputs = {
    nixpkgs.url = "https://flakehub.com/f/NixOS/nixpkgs/*";
    flake-compat.url = "https://flakehub.com/f/edolstra/flake-compat/*";
    flake-schemas.url = "https://flakehub.com/f/DeterminateSystems/flake-schemas/*";
  };

  # Flake outputs that other flakes can use
  outputs = { self, flake-compat, flake-schemas, nixpkgs }:
    let
      # Helpers for producing system-specific outputs
      supportedSystems = [ "x86_64-linux" "aarch64-darwin" "x86_64-darwin" "aarch64-linux" ];
      forEachSupportedSystem = f: nixpkgs.lib.genAttrs supportedSystems (system: f {
        pkgs = import nixpkgs { inherit system; };
      });

      linuxPkgs = nixpkgs.legacyPackages.x86_64-linux;
    in
    {
      # Schemas tell Nix about the structure of your flake's outputs
      inherit (flake-schemas) schemas;

      formatter = forEachSupportedSystem ({ pkgs }: pkgs.nixpkgs-fmt);

      dockerImages = forEachSupportedSystem ({ pkgs }: {
        server = pkgs.dockerTools.buildLayeredImage {
          name = "static-web-server";
          contents = with linuxPkgs; [ cacert ];
          config = {
            Entrypoint = [ "${linuxPkgs.static-web-server}/bin/static-web-server" ];
          };
        };
      });

      # Development environments
      devShells = forEachSupportedSystem ({ pkgs }: {
        default = pkgs.mkShell {
          # Pinned packages available in the environment
          packages = with pkgs; [ ];
        };
      });
    };
}
