name: Publish every Git push to main to FlakeHub

on:
  push:
    branches:
      - main

jobs:
  build-and-cache:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Build and cache NixOS configuration
        run: |
          nix build .#nixosConfigurations.baseline.config.system.build.toplevel

  flakehub-publish:
    runs-on: ubuntu-22.04
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/flakehub-push@main
        with:
          name: DeterminateSystems/store-paths
          rolling: true
          visibility: public
          include-output-paths: true
