name: Build/cache all outputs and publish rolling release to FlakeHub

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-linux:
    runs-on: ubuntu-22.04
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - run: |
          nix build ".#packages.x86_64-linux.server"
          nix build "#nixosConfigurations.baseline.config.system.build.toplevel"

  build-docker-image:
    runs-on: ${{ matrix.systems.runner }}
    needs: build-linux
    permissions:
      id-token: write
      contents: read
    strategy:
      matrix:
        systems:
          - nix-system: x86_64-linux
            runner: ubuntu-22.04
          - nix-system: aarch64-darwin
            runner: macos-latest-xlarge
          - nix-system: x86_64-darwin
            runner: macos-12
          - nix-system: aarch64-linux
            runner: namespace-profile-default-arm64

    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Build Docker image for ${{ matrix.systems.nix-system }}
        run: |
          nix build ".#dockerImages.${{ matrix.systems.nix-system }}.server"

  flakehub-publish:
    runs-on: ubuntu-22.04
    needs: build-docker-image
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/flakehub-push@main
        with:
          name: DeterminateSystems/store-paths
          rolling: true
          visibility: public
          include-output-paths: true
